version: "2"
run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
  exclusions:
    rules:
      - linters:
          - errcheck
        text: "Error return value of.*\\.(Close|Disconnect).* is not checked"
