profile: cover

threshold:
  file: 0
  package: 0
  total: 0

exclude:
  paths:
    - ^cmd/
    - /port/
    - /config/
    - ^docs/
    - /serviceerrors/
    - /logger/
    - /mock/
    - /document/
    - /dto/
    - router.go