// Code generated by MockGen. DO NOT EDIT.
// Source: broker.go
//
// Generated by this command:
//
//	mockgen -source=broker.go -destination=mock/broker.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/rafaelleal24/challenge/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBrokerPort is a mock of BrokerPort interface.
type MockBrokerPort struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerPortMockRecorder
	isgomock struct{}
}

// MockBrokerPortMockRecorder is the mock recorder for MockBrokerPort.
type MockBrokerPortMockRecorder struct {
	mock *MockBrokerPort
}

// NewMockBrokerPort creates a new mock instance.
func NewMockBrokerPort(ctrl *gomock.Controller) *MockBrokerPort {
	mock := &MockBrokerPort{ctrl: ctrl}
	mock.recorder = &MockBrokerPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerPort) EXPECT() *MockBrokerPortMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBrokerPort) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBrokerPortMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrokerPort)(nil).Close))
}

// Publish mocks base method.
func (m *MockBrokerPort) Publish(ctx context.Context, event domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockBrokerPortMockRecorder) Publish(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockBrokerPort)(nil).Publish), ctx, event)
}

// PublishRaw mocks base method.
func (m *MockBrokerPort) PublishRaw(ctx context.Context, eventName, entityName string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRaw", ctx, eventName, entityName, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRaw indicates an expected call of PublishRaw.
func (mr *MockBrokerPortMockRecorder) PublishRaw(ctx, eventName, entityName, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRaw", reflect.TypeOf((*MockBrokerPort)(nil).PublishRaw), ctx, eventName, entityName, data)
}
