// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=mock/cache.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCachePort is a mock of CachePort interface.
type MockCachePort[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockCachePortMockRecorder[T]
	isgomock struct{}
}

// MockCachePortMockRecorder is the mock recorder for MockCachePort.
type MockCachePortMockRecorder[T any] struct {
	mock *MockCachePort[T]
}

// NewMockCachePort creates a new mock instance.
func NewMockCachePort[T any](ctrl *gomock.Controller) *MockCachePort[T] {
	mock := &MockCachePort[T]{ctrl: ctrl}
	mock.recorder = &MockCachePortMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachePort[T]) EXPECT() *MockCachePortMockRecorder[T] {
	return m.recorder
}

// Del mocks base method.
func (m *MockCachePort[T]) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockCachePortMockRecorder[T]) Del(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCachePort[T])(nil).Del), ctx, key)
}

// Get mocks base method.
func (m *MockCachePort[T]) Get(ctx context.Context, key string) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCachePortMockRecorder[T]) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCachePort[T])(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockCachePort[T]) Set(ctx context.Context, key string, value *T, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCachePortMockRecorder[T]) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCachePort[T])(nil).Set), ctx, key, value, ttl)
}

// SetNX mocks base method.
func (m *MockCachePort[T]) SetNX(ctx context.Context, key string, value *T, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNX", ctx, key, value, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNX indicates an expected call of SetNX.
func (mr *MockCachePortMockRecorder[T]) SetNX(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNX", reflect.TypeOf((*MockCachePort[T])(nil).SetNX), ctx, key, value, ttl)
}
