// Code generated by MockGen. DO NOT EDIT.
// Source: customer.go
//
// Generated by this command:
//
//	mockgen -source=customer.go -destination=mock/customer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/rafaelleal24/challenge/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerPort is a mock of CustomerPort interface.
type MockCustomerPort struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerPortMockRecorder
	isgomock struct{}
}

// MockCustomerPortMockRecorder is the mock recorder for MockCustomerPort.
type MockCustomerPortMockRecorder struct {
	mock *MockCustomerPort
}

// NewMockCustomerPort creates a new mock instance.
func NewMockCustomerPort(ctrl *gomock.Controller) *MockCustomerPort {
	mock := &MockCustomerPort{ctrl: ctrl}
	mock.recorder = &MockCustomerPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerPort) EXPECT() *MockCustomerPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerPort) Create(ctx context.Context) (domain.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx)
	ret0, _ := ret[0].(domain.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerPortMockRecorder) Create(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerPort)(nil).Create), ctx)
}

// Exists mocks base method.
func (m *MockCustomerPort) Exists(ctx context.Context, id domain.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockCustomerPortMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockCustomerPort)(nil).Exists), ctx, id)
}
