// Code generated by MockGen. DO NOT EDIT.
// Source: order.go
//
// Generated by this command:
//
//	mockgen -source=order.go -destination=mock/order.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/rafaelleal24/challenge/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderPort is a mock of OrderPort interface.
type MockOrderPort struct {
	ctrl     *gomock.Controller
	recorder *MockOrderPortMockRecorder
	isgomock struct{}
}

// MockOrderPortMockRecorder is the mock recorder for MockOrderPort.
type MockOrderPortMockRecorder struct {
	mock *MockOrderPort
}

// NewMockOrderPort creates a new mock instance.
func NewMockOrderPort(ctrl *gomock.Controller) *MockOrderPort {
	mock := &MockOrderPort{ctrl: ctrl}
	mock.recorder = &MockOrderPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderPort) EXPECT() *MockOrderPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderPort) Create(ctx context.Context, order *domain.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderPortMockRecorder) Create(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderPort)(nil).Create), ctx, order)
}

// Delete mocks base method.
func (m *MockOrderPort) Delete(ctx context.Context, id domain.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderPortMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderPort)(nil).Delete), ctx, id)
}

// GetByCustomerID mocks base method.
func (m *MockOrderPort) GetByCustomerID(ctx context.Context, customerID domain.ID, limit, offset int64) ([]*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCustomerID", ctx, customerID, limit, offset)
	ret0, _ := ret[0].([]*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCustomerID indicates an expected call of GetByCustomerID.
func (mr *MockOrderPortMockRecorder) GetByCustomerID(ctx, customerID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCustomerID", reflect.TypeOf((*MockOrderPort)(nil).GetByCustomerID), ctx, customerID, limit, offset)
}

// GetByID mocks base method.
func (m *MockOrderPort) GetByID(ctx context.Context, id domain.ID) (*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrderPortMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrderPort)(nil).GetByID), ctx, id)
}

// GetByStatus mocks base method.
func (m *MockOrderPort) GetByStatus(ctx context.Context, status domain.OrderStatus, limit, offset int64) ([]*domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStatus", ctx, status, limit, offset)
	ret0, _ := ret[0].([]*domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStatus indicates an expected call of GetByStatus.
func (mr *MockOrderPortMockRecorder) GetByStatus(ctx, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStatus", reflect.TypeOf((*MockOrderPort)(nil).GetByStatus), ctx, status, limit, offset)
}

// UpdateStatusWithOutbox mocks base method.
func (m *MockOrderPort) UpdateStatusWithOutbox(ctx context.Context, id domain.ID, status domain.OrderStatus, event domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusWithOutbox", ctx, id, status, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusWithOutbox indicates an expected call of UpdateStatusWithOutbox.
func (mr *MockOrderPortMockRecorder) UpdateStatusWithOutbox(ctx, id, status, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusWithOutbox", reflect.TypeOf((*MockOrderPort)(nil).UpdateStatusWithOutbox), ctx, id, status, event)
}
