// Code generated by MockGen. DO NOT EDIT.
// Source: product.go
//
// Generated by this command:
//
//	mockgen -source=product.go -destination=mock/product.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/rafaelleal24/challenge/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockProductPort is a mock of ProductPort interface.
type MockProductPort struct {
	ctrl     *gomock.Controller
	recorder *MockProductPortMockRecorder
	isgomock struct{}
}

// MockProductPortMockRecorder is the mock recorder for MockProductPort.
type MockProductPortMockRecorder struct {
	mock *MockProductPort
}

// NewMockProductPort creates a new mock instance.
func NewMockProductPort(ctrl *gomock.Controller) *MockProductPort {
	mock := &MockProductPort{ctrl: ctrl}
	mock.recorder = &MockProductPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductPort) EXPECT() *MockProductPortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductPort) Create(ctx context.Context, product *domain.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductPortMockRecorder) Create(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductPort)(nil).Create), ctx, product)
}

// DeductStock mocks base method.
func (m *MockProductPort) DeductStock(ctx context.Context, id domain.ID, quantity int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductStock", ctx, id, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeductStock indicates an expected call of DeductStock.
func (mr *MockProductPortMockRecorder) DeductStock(ctx, id, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductStock", reflect.TypeOf((*MockProductPort)(nil).DeductStock), ctx, id, quantity)
}

// GetAll mocks base method.
func (m *MockProductPort) GetAll(ctx context.Context) ([]*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockProductPortMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockProductPort)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockProductPort) GetByID(ctx context.Context, id domain.ID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProductPortMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProductPort)(nil).GetByID), ctx, id)
}
